from __future__ import annotations

import json
import logging
import os
import plistlib
import re
import threading
import time
from pathlib import Path
from typing import Any, Callable

import pytest
from websockets.sync.server import serve

from obed_edom import managed_obs
from obed_edom.managed_obs import (
    DECKLINK_PROPS,
    PAGE_URL,
    PINNED_OBS,
    ManagedObs,
    ManagedObsError,
    ObsProcess,
    TreeConfig,
    last_version,
    render_tree,
    write_tree,
)
from obed_edom.obs_websocket import ObsWebsocketTimeout
from tests.test_obs_websocket import FakeObsWebsocket

# ---------------------------------------------------------------------------
# Goldens: verbatim output of the spike's seed.py (main checkout
# output/obs-managed-spike/scripts/seed.py) run as `seed.py <home> 25 50 <rec>`
# on 2026-09-24. They are NOT generated by the code under test.
# ---------------------------------------------------------------------------
SPIKE_REC = "/SPIKE/rec"
SPIKE_GLOBAL_INI = "[General]\nLastVersion=537001986\nMacOSPermissionsDialogLastShown=1\n"
SPIKE_USER_INI = (
    "[General]\nPre19Defaults=false\nPre21Defaults=false\nPre23Defaults=false\nPre24.1Defaults=false\nFirstRun=true\n"
    "\n[Basic]\nProfile=AK\nProfileDir=AK\nSceneCollection=AK\nSceneCollectionFile=AK.json\nConfigOnNewProfile=false\n"
)
SPIKE_BASIC_INI_25 = (
    "[General]\nName=AK\n\n[Video]\nBaseCX=1920\nBaseCY=1080\nOutputCX=1920\nOutputCY=1080\nFPSType=0\nFPSCommon=25 PAL\n"
    "ColorFormat=NV12\nColorSpace=709\nColorRange=Partial\n\n[Output]\nMode=Simple\n\n"
    f"[SimpleOutput]\nFilePath={SPIKE_REC}\nRecFilePath={SPIKE_REC}\nRecFormat2=hybrid_mov\nRecQuality=Lossless\nRecRB=false\n\n"
    "[Audio]\nSampleRate=48000\nChannelSetup=Stereo\n"
)
SPIKE_SIMPLE_OUTPUT_BLOCK = (
    f"[SimpleOutput]\nFilePath={SPIKE_REC}\nRecFilePath={SPIKE_REC}\nRecFormat2=hybrid_mov\nRecQuality=Lossless\nRecRB=false\n\n"
)
SPIKE_WS_CONFIG = {"first_load": False, "server_enabled": True, "server_port": 4455, "alerts_enabled": False,
                   "auth_required": True, "server_password": "tvDJIiihm0c5OB5oxthmk8xc"}
SPIKE_SCENES_25 = json.loads(
    '{"name":"AK","sources":[{"prev_ver":537001986,"name":"Program","uuid":"e170399f-a808-4831-a223-15f800f6c88d",'
    '"id":"browser_source","versioned_id":"browser_source","settings":{"url":"about:blank#program","width":1920,'
    '"height":1080,"fps":50,"fps_custom":true,"shutdown":false,"reroute_audio":false},"hotkeys":{},"mixers":0,"sync":0,'
    '"flags":0,"volume":1.0,"balance":0.5,"enabled":true,"muted":false,"push-to-mute":false,"push-to-mute-delay":0,'
    '"push-to-talk":false,"push-to-talk-delay":0,"deinterlace_mode":0,"deinterlace_field_order":0,"monitoring_type":0,'
    '"private_settings":{}},{"prev_ver":537001986,"name":"AK","uuid":"e506ce6b-0014-4ccc-8088-31768512ee3c","id":"scene",'
    '"versioned_id":"scene","settings":{"id_counter":1,"custom_size":false,"items":[{"name":"Program",'
    '"source_uuid":"e170399f-a808-4831-a223-15f800f6c88d","visible":true,"locked":true,"rot":0.0,'
    '"scale_ref":{"x":1920.0,"y":1080.0},"align":5,"bounds_type":2,"bounds_align":0,"bounds_crop":false,"crop_left":0,'
    '"crop_top":0,"crop_right":0,"crop_bottom":0,"id":1,"group_item_backup":false,"pos":{"x":0.0,"y":0.0},'
    '"scale":{"x":1.0,"y":1.0},"bounds":{"x":1920.0,"y":1080.0},"scale_filter":"disable","blend_method":"default",'
    '"blend_type":"normal","show_transition":{"duration":300},"hide_transition":{"duration":300},"private_settings":{}}]},'
    '"hotkeys":{},"canvas_uuid":"6c69626f-6273-4c00-9d88-c5136d61696e","mixers":0,"sync":0,"flags":0,"volume":1.0,'
    '"balance":0.5,"enabled":true,"muted":false,"push-to-mute":false,"push-to-mute-delay":0,"push-to-talk":false,'
    '"push-to-talk-delay":0,"deinterlace_mode":0,"deinterlace_field_order":0,"monitoring_type":0,"private_settings":{}}],'
    '"groups":[],"scene_order":[{"name":"AK"}],"current_scene":"AK","current_program_scene":"AK","canvases":[],'
    '"current_transition":"Cut","transition_duration":300,"transitions":[],"quick_transitions":[{"name":"Cut",'
    '"duration":300,"hotkeys":[],"id":1,"fade_to_black":false}],"saved_projectors":[],"preview_locked":true,'
    '"scaling_enabled":false,"scaling_level":0,"scaling_off_x":0.0,"scaling_off_y":0.0,"modules":{},'
    '"resolution":{"x":1920,"y":1080},"version":2}'
)

UUID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")
DEVICE = {"deviceHash": "hash-ultrastudio", "deviceName": "UltraStudio HD Mini", "modeIds": {"25": 1215313201}, "pixelFormat": 1111970369}


def _cfg(**overrides: Any) -> TreeConfig:
    values: dict[str, Any] = {"rate": 25, "keyer": "external", "ws_port": 51234, "ws_password": "pw"}
    values.update(overrides)
    return TreeConfig(**values)


def _normalise_scenes(collection: dict[str, Any]) -> dict[str, Any]:
    """Blank the per-run fields the plan excludes from the golden (uuids, page url)."""
    collection = json.loads(json.dumps(collection))
    browser, scene = collection["sources"]
    browser["uuid"] = scene["uuid"] = "UUID"
    scene["settings"]["items"][0]["source_uuid"] = "UUID"
    browser["settings"]["url"] = "URL"
    return collection


# --- render_tree goldens ----------------------------------------------------


def test_last_version_formula_matches_spike():
    assert last_version("32.2.2") == 537001986
    assert last_version("32.2.2") == (32 << 24) | (2 << 16) | 2
    assert last_version("31.0.0") == 31 << 24


def test_render_tree_rate_25_matches_spike_seed_golden():
    files = render_tree(_cfg(record_dir=Path(SPIKE_REC)))
    assert files["global.ini"].decode() == SPIKE_GLOBAL_INI
    assert files["user.ini"].decode() == SPIKE_USER_INI
    assert files["basic/profiles/AK/basic.ini"].decode() == SPIKE_BASIC_INI_25
    assert _normalise_scenes(json.loads(files["basic/scenes/AK.json"])) == _normalise_scenes(SPIKE_SCENES_25)
    ws = json.loads(files["plugin_config/obs-websocket/config.json"])
    assert {k: v for k, v in ws.items() if k not in ("server_port", "server_password")} == {
        k: v for k, v in SPIKE_WS_CONFIG.items() if k not in ("server_port", "server_password")
    }


def test_product_profile_is_the_golden_without_recording_keys():
    text = render_tree(_cfg())["basic/profiles/AK/basic.ini"].decode()
    assert text == SPIKE_BASIC_INI_25.replace(SPIKE_SIMPLE_OUTPUT_BLOCK, "")
    assert "Rec" not in text and "FilePath" not in text


def test_render_tree_page_url_uuids_port_and_password():
    files = render_tree(_cfg(ws_port=40001, ws_password="secret-pw"))
    collection = json.loads(files["basic/scenes/AK.json"])
    browser, scene = collection["sources"]
    assert browser["settings"]["url"] == PAGE_URL == "about:blank#obed-ak"
    assert UUID_RE.match(browser["uuid"]) and UUID_RE.match(scene["uuid"]) and browser["uuid"] != scene["uuid"]
    assert scene["settings"]["items"][0]["source_uuid"] == browser["uuid"]
    ws = json.loads(files["plugin_config/obs-websocket/config.json"])
    assert ws["server_port"] == 40001 and ws["server_password"] == "secret-pw"
    assert ws["server_enabled"] is True and ws["auth_required"] is True


def test_render_tree_has_no_audio_capture_sources():
    collection = json.loads(render_tree(_cfg())["basic/scenes/AK.json"])
    assert [source["id"] for source in collection["sources"]] == ["browser_source", "scene"]
    assert collection["sources"][0]["settings"]["reroute_audio"] is False


@pytest.mark.parametrize("rate, canvas, source", [(25, "25 PAL", 50), (30, "30", 60)])
def test_rate_table(rate, canvas, source):
    files = render_tree(_cfg(rate=rate))
    assert f"\nFPSCommon={canvas}\n" in files["basic/profiles/AK/basic.ini"].decode()
    browser = json.loads(files["basic/scenes/AK.json"])["sources"][0]
    assert browser["settings"]["fps"] == source and browser["settings"]["fps_custom"] is True
    assert managed_obs.rate_info(rate) == {"output": rate, "canvas": canvas, "source": source}


@pytest.mark.parametrize("bad", [{"rate": 50}, {"rate": 24}, {"keyer": "internal"}])
def test_render_tree_rejects_unsupported_rate_or_keyer(bad):
    with pytest.raises(ValueError):
        render_tree(_cfg(**bad))


def test_decklink_file_only_when_a_device_is_recorded_for_the_rate():
    assert DECKLINK_PROPS not in render_tree(_cfg())
    assert DECKLINK_PROPS not in render_tree(_cfg(device={"deviceHash": "h", "modeIds": {}}))
    assert DECKLINK_PROPS not in render_tree(_cfg(rate=30, device=DEVICE))
    props = json.loads(render_tree(_cfg(device=DEVICE))[DECKLINK_PROPS])
    assert props == {"device_hash": "hash-ultrastudio", "device_name": "UltraStudio HD Mini", "mode_id": 1215313201,
                     "keyer": 1, "auto_start": True, "pixel_format": 1111970369}


@pytest.mark.parametrize("keyer, value", [("external", 1), ("off", 0)])
def test_decklink_keyer_value(keyer, value):
    props = json.loads(render_tree(_cfg(keyer=keyer, device=DEVICE))[DECKLINK_PROPS])
    assert props["keyer"] == value and props["auto_start"] is True


def test_write_tree_writes_only_the_given_files(tmp_path):
    (tmp_path / ".sentinel").mkdir()
    (tmp_path / ".sentinel" / "run_1").write_bytes(b"x")
    write_tree(tmp_path, {"a/b.ini": b"1", "c.json": b"2"})
    assert (tmp_path / "a/b.ini").read_bytes() == b"1"
    assert (tmp_path / "c.json").read_bytes() == b"2"
    assert (tmp_path / ".sentinel" / "run_1").read_bytes() == b"x"


# --- fakes ------------------------------------------------------------------


class FakeClock:
    def __init__(self) -> None:
        self.now = 1000.0

    def __call__(self) -> float:
        return self.now

    def sleep(self, seconds: float) -> None:
        self.now += seconds


class FakeCdp:
    """Serves `/json/list` over HTTP and page websockets on the same loopback port."""

    def __init__(self) -> None:
        self.navigations: list[tuple[str, str]] = []
        self.server = serve(self._handler, "127.0.0.1", 0, process_request=self._http)
        self.port = int(self.server.socket.getsockname()[1])
        self.targets: list[dict[str, Any]] = [self.page("T1", PAGE_URL)]
        threading.Thread(target=self.server.serve_forever, daemon=True).start()

    def page(self, target_id: str, url: str) -> dict[str, Any]:
        return {"id": target_id, "type": "page", "url": url, "title": "", "webSocketDebuggerUrl": f"ws://127.0.0.1:{self.port}/devtools/page/{target_id}"}

    def _http(self, connection: Any, request: Any) -> Any:
        if request.path == "/json/list":
            return connection.respond(200, json.dumps(self.targets))
        return None

    def _handler(self, ws: Any) -> None:
        target = ws.request.path.rsplit("/", 1)[-1]
        for raw in ws:
            message = json.loads(raw)
            self.navigations.append((target, message["params"]["url"]))
            ws.send(json.dumps({"id": message["id"], "result": {"frameId": "F"}}))

    def close(self) -> None:
        self.server.shutdown()


class FakeLauncher:
    """Fake OBS processes: `alive_pids` are running OBS apps, `dates` their launch dates and
    `homes` the CFFIXED_USER_HOME each was started with (None: no marker)."""

    def __init__(self) -> None:
        self.launches: list[dict[str, Any]] = []
        self.alive_pids: set[int] = set()
        self.dates: dict[int, float | None] = {}
        self.homes: dict[int, str | None] = {}
        self.marker_unknown: set[int] = set()
        self.processes_fail = False
        self.stale: list[ObsProcess] = []
        self.terminated: list[int] = []
        self.shown: list[int] = []
        self.quits = True
        self.next_pid = 4242
        self.launch_date: Callable[[], float | None] = time.time
        self.block: threading.Event | None = None
        self.entered = threading.Event()
        self.on_launch: Callable[["FakeLauncher", int], None] | None = None
        self.on_terminate: Callable[[int], None] | None = None

    def add(self, pid: int, date: float | None, home: Path | str | None) -> None:
        self.alive_pids.add(pid)
        self.dates[pid] = date
        self.homes[pid] = None if home is None else str(home)

    def launch(self, app, args, env, *, hidden, on_launched):
        self.entered.set()
        if self.block is not None:
            assert self.block.wait(15)
        pid = self.next_pid
        self.next_pid += 1
        self.add(pid, self.launch_date(), env.get("CFFIXED_USER_HOME"))
        self.launches.append({"app": app, "args": list(args), "env": dict(env), "hidden": hidden, "pid": pid})
        on_launched(pid, self.dates[pid])
        if self.on_launch is not None:
            self.on_launch(self, pid)
        return pid, self.dates[pid]

    def processes(self):
        if self.processes_fail:
            raise OSError("LaunchServices unavailable")
        return [ObsProcess(pid, self.dates.get(pid), handle=("app", pid, self.dates.get(pid))) for pid in sorted(self.alive_pids)]

    def _verified(self, process):
        live = ("app", process.pid, self.dates.get(process.pid))
        return process.pid in self.alive_pids and process.handle == live

    def env_marker(self, pid, home):
        if pid in self.marker_unknown:
            return None
        return pid in self.alive_pids and self.homes.get(pid) == str(home)

    def terminate(self, process):
        if not self._verified(process):
            return False
        pid = process.pid
        self.terminated.append(pid)
        if self.on_terminate is not None:
            self.on_terminate(pid)
        if self.quits:
            self.alive_pids.discard(pid)
        return True

    def show(self, process):
        if not self._verified(process):
            return False
        self.shown.append(process.pid)
        return True


def _fake_app(root: Path, version: str = PINNED_OBS, bundle_id: str = "com.obsproject.obs-studio") -> Path:
    app = root / "OBS.app"
    (app / "Contents").mkdir(parents=True, exist_ok=True)
    with (app / "Contents/Info.plist").open("wb") as handle:
        plistlib.dump({"CFBundleIdentifier": bundle_id, "CFBundleShortVersionString": version}, handle)
    return app


class Rig:
    """A ManagedObs wired to a fake launcher, fake CDP and a fake obs-websocket that reads
    the password from the seeded tree, the way OBS does."""

    def __init__(self, tmp_path: Path, *, version: str = PINNED_OBS, output_active: bool | None = True, ws_alive: bool = True) -> None:
        self.home = tmp_path / "home"
        self.clock = FakeClock()
        self.launcher = FakeLauncher()
        self.cdp = FakeCdp()
        self.ws = FakeObsWebsocket(self._tree_password, version=version, output_active=output_active)
        self.ws_port = self.ws.port if ws_alive else managed_obs.free_port()
        self._ports: list[int] = []
        self.engines: list[ManagedObs] = []
        self.app = _fake_app(tmp_path)
        self.engine = self.make()

    def _tree_password(self) -> str | None:
        config = self.home / managed_obs.TREE_RELPATH / "plugin_config/obs-websocket/config.json"
        return json.loads(config.read_text())["server_password"]

    def _pick_port(self) -> int:
        if not self._ports:
            self._ports = [self.cdp.port, self.ws_port]
        return self._ports.pop(0)

    def make(self, **overrides: Any) -> ManagedObs:
        options: dict[str, Any] = {"launcher": self.launcher, "clock": self.clock, "sleep": self.clock.sleep, "obs_app": self.app,
                                   "pick_port": self._pick_port, "ready_timeout_s": 2.0, "liveness_s": 3600.0}
        options.update(overrides)
        engine = ManagedObs(self.home, **options)
        self.engines.append(engine)
        return engine

    @property
    def tree(self) -> Path:
        return self.home / managed_obs.TREE_RELPATH

    def record(self) -> dict[str, Any]:
        return json.loads((self.home / "ak-engine.json").read_text())

    def run(self, action: Callable[[], None], engine: ManagedObs | None = None) -> dict[str, Any]:
        engine = engine or self.engine
        action()
        assert engine.wait_idle(15)
        return engine.state()

    def close(self) -> None:
        if self.launcher.block is not None:
            self.launcher.block.set()
        for engine in self.engines:
            engine.close()
        self.cdp.close()
        self.ws.close()


@pytest.fixture
def rig(tmp_path):
    rigs: list[Rig] = []

    def make(**kwargs: Any) -> Rig:
        made = Rig(tmp_path / f"rig{len(rigs)}", **kwargs)
        rigs.append(made)
        return made

    yield make
    for made in rigs:
        made.close()


def _ids(state: dict[str, Any]) -> list[str]:
    return [warning["id"] for warning in state["warnings"]]


# --- launch configuration -----------------------------------------------------


def test_launch_configuration_hidden(rig):
    r = rig()
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["state"] == "ready"
    launch = r.launcher.launches[0]
    assert launch["app"] == r.app
    assert launch["hidden"] is True
    assert launch["args"] == ["--multi", "--disable-updater", "--disable-missing-files-check", "--minimize-to-tray",
                              f"--remote-debugging-port={r.cdp.port}"]
    assert launch["env"] == {"CFFIXED_USER_HOME": str(r.home), "HOME": str(r.home)}
    assert r.engine.cdp_endpoint == f"http://127.0.0.1:{r.cdp.port}"
    assert r.engine.target_id == "T1"
    assert state["obs"] == {"path": str(r.app), "version": PINNED_OBS, "pinned": PINNED_OBS}
    assert state["rate"] == {"output": 25, "canvas": "25 PAL", "source": 50}
    assert state["keyer"] == "external"


def test_ensure_started_is_idempotent_and_non_blocking(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["state"] == "ready"
    assert len(r.launcher.launches) == 1
    assert r.launcher.terminated == []


def test_ensure_started_with_a_new_rate_restarts(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    state = r.run(lambda: r.engine.ensure_started(30, "off"))
    assert state["state"] == "ready"
    assert r.launcher.terminated == [4242]
    assert len(r.launcher.launches) == 2
    assert state["rate"] == {"output": 30, "canvas": "30", "source": 60}
    assert "FPSCommon=30\n" in (r.tree / "basic/profiles/AK/basic.ini").read_text()


def test_invalid_rate_or_keyer_is_rejected_synchronously(rig):
    r = rig()
    with pytest.raises(ValueError):
        r.engine.ensure_started(50, "external")
    with pytest.raises(ValueError):
        r.engine.restart(25, "internal")
    assert r.launcher.launches == []


def test_engine_record_written_with_ports_and_clean_exit(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    record = r.record()
    assert record["pid"] == 4242
    assert record["cdpPort"] == r.cdp.port and record["wsPort"] == r.ws.port
    assert record["cleanExit"] is False
    assert isinstance(record["launchDate"], float)
    r.run(r.engine.quit)
    assert r.record()["cleanExit"] is True


def test_record_written_only_once_launch_returned_a_pid(rig):
    r = rig()
    seen: dict[str, Any] = {}
    original = r.engine._seed

    def spy(cfg):
        seen["exists"] = (r.home / "ak-engine.json").exists()
        original(cfg)

    r.engine._seed = spy
    r.run(lambda: r.engine.ensure_started(25, "external"))
    assert seen["exists"] is False
    assert r.record()["pid"] == 4242 and r.record()["cleanExit"] is False


def test_failed_launch_writes_no_record_and_no_w3_next_time(rig):
    r = rig()
    real_launch = r.launcher.launch

    def failing(*args, **kwargs):
        raise ManagedObsError("OBS could not be launched")

    r.launcher.launch = failing
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["reason"] == "engineError"
    assert not (r.home / "ak-engine.json").exists()
    r.launcher.launch = real_launch
    state = r.run(lambda: r.engine.restart(25, "external"))
    assert state["state"] == "ready" and "obsUncleanExit" not in _ids(state)


# --- discovery ----------------------------------------------------------------


def test_missing_obs_is_w1_unavailable(rig, tmp_path):
    r = rig()
    r.engine = ManagedObs(r.home, launcher=r.launcher, obs_app=tmp_path / "nowhere/OBS.app")
    r.engines.append(r.engine)
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["state"] == "unavailable" and state["reason"] == "obsMissing"
    w1 = state["warnings"][0]
    assert w1 == {"id": "obsMissing", "severity": "block", "action": "check",
                  "text": "Output engine not installed. Install OBS 32.2.2 into Applications, then press Check again."}
    assert r.launcher.launches == []


def test_wrong_plist_version_is_w2_unavailable(rig, tmp_path):
    r = rig()
    _fake_app(r.app.parent, version="31.1.0")
    state = r.run(r.engine.check)
    assert state["state"] == "unavailable"
    assert state["warnings"][0]["text"] == "Output engine is OBS 31.1.0; Alpha Keynote needs OBS 32.2.2. Install 32.2.2, then press Check again."
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert r.launcher.launches == []
    _fake_app(r.app.parent)
    assert r.run(r.engine.check)["state"] == "stopped"


# --- readiness matrix -------------------------------------------------------


def test_readiness_ready(rig):
    r = rig()
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["state"] == "ready" and "reason" not in state
    assert [request[0] for request in r.ws.requests] == ["GetVersion"]
    assert _ids(state) == ["noDevice"]


def test_readiness_safe_mode_from_log(rig):
    r = rig()

    def write_log(launcher, pid):
        logs = r.tree / "logs"
        logs.mkdir(parents=True, exist_ok=True)
        (logs / "2026-09-24 10-00-00.txt").write_text("10:00:00.000: [Safe Mode] Safe mode launch selected, loading third-party plugins is disabled\n")

    r.launcher.on_launch = write_log
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["state"] == "blocked" and state["reason"] == "safeMode"
    assert "obsSafeMode" in _ids(state)


def test_old_safe_mode_log_is_ignored(rig):
    r = rig()
    logs = r.tree / "logs"
    logs.mkdir(parents=True)
    old = logs / "2026-09-20 10-00-00.txt"
    old.write_text("[Safe Mode] Safe mode launch selected\n")
    os.utime(old, (time.time() - 3600, time.time() - 3600))
    assert r.run(lambda: r.engine.ensure_started(25, "external"))["state"] == "ready"


def test_readiness_timeout_is_w3b(rig):
    r = rig()
    r.cdp.targets = []
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["state"] == "blocked" and state["reason"] == "timeout"
    w3b = next(w for w in state["warnings"] if w["id"] == "obsWaiting")
    assert w3b["text"] == "OBS is waiting for an answer or a permission. Press Show OBS, answer it, then press Check again."
    assert w3b["severity"] == "block"
    r.cdp.targets = [r.cdp.page("T1", PAGE_URL)]
    state = r.run(r.engine.check)
    assert state["state"] == "ready" and "obsWaiting" not in _ids(state)
    assert len(r.launcher.launches) == 1


def test_two_marked_pages_are_not_ready(rig):
    r = rig()
    r.cdp.targets = [r.cdp.page("T1", PAGE_URL), r.cdp.page("T2", PAGE_URL)]
    assert r.run(lambda: r.engine.ensure_started(25, "external"))["reason"] == "timeout"


def test_cdp_up_websocket_down_is_w4(rig):
    r = rig(ws_alive=False)
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["state"] == "blocked" and state["reason"] == "safeMode"
    w4 = next(w for w in state["warnings"] if w["id"] == "obsSafeMode")
    assert w4["text"] == "OBS started in Safe Mode, so Alpha Keynote cannot watch it. Press Restart output engine and choose Normal Mode when OBS asks."


def test_readiness_exited(rig):
    r = rig()
    r.launcher.on_launch = lambda launcher, pid: launcher.alive_pids.discard(pid)
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["state"] == "blocked" and state["reason"] == "exited"
    assert "obsExited" in _ids(state)
    assert r.engine.cdp_endpoint is None


def test_readiness_wrong_websocket_version_is_w2(rig):
    r = rig(version="32.3.0")
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["state"] == "blocked" and state["reason"] == "obsVersion"
    w2 = next(w for w in state["warnings"] if w["id"] == "obsVersion")
    assert w2["text"] == "Output engine is OBS 32.3.0; Alpha Keynote needs OBS 32.2.2. Install 32.2.2, then press Check again."
    state = r.run(r.engine.check)
    assert state["reason"] == "obsVersion" and "obsVersion" in _ids(state)


# --- liveness ---------------------------------------------------------------


def test_liveness_follows_the_target_id_not_the_url(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.cdp.targets = [r.cdp.page("T1", "http://127.0.0.1:9/program.html")]
    r.engine._liveness()
    assert r.engine.state()["state"] == "ready"
    r.cdp.targets = [r.cdp.page("T9", PAGE_URL)]
    r.engine._liveness()
    state = r.engine.state()
    assert state["state"] == "blocked" and state["reason"] == "pageLost"


def test_liveness_vanished_pid_is_w5(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.launcher.alive_pids.clear()
    r.engine._liveness()
    state = r.engine.state()
    assert state["state"] == "blocked" and state["reason"] == "exited"
    w5 = next(w for w in state["warnings"] if w["id"] == "obsExited")
    assert w5 == {"id": "obsExited", "severity": "block", "action": "restart",
                  "text": "OBS stopped unexpectedly — nothing is going to the keyer. Press Restart output engine. OBS may then ask a question (see Show OBS)."}
    assert r.record()["cleanExit"] is False


def test_check_runs_liveness_when_ready(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.launcher.alive_pids.clear()
    assert r.run(r.engine.check)["reason"] == "exited"


def test_engine_thread_runs_liveness_on_its_own(rig):
    r = rig()
    r.engine = ManagedObs(r.home, launcher=r.launcher, clock=r.clock, sleep=r.clock.sleep, obs_app=r.app,
                          pick_port=r._pick_port, ready_timeout_s=2.0, liveness_s=0.05)
    r.engines.append(r.engine)
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.launcher.alive_pids.clear()
    deadline = time.monotonic() + 5
    while r.engine.state()["state"] == "ready" and time.monotonic() < deadline:
        time.sleep(0.02)
    assert r.engine.state()["reason"] == "exited"


# --- device ---------------------------------------------------------------


def _record_device(home: Path, device: dict[str, Any] = DEVICE) -> None:
    home.mkdir(parents=True, exist_ok=True)
    (home / "ak-device.json").write_text(json.dumps(device))


def test_no_device_is_w9(rig):
    r = rig()
    w9 = next(w for w in r.engine.state()["warnings"] if w["id"] == "noDevice")
    assert w9 == {"id": "noDevice", "severity": "warn", "action": "setupDevice",
                  "text": "No output device set for 25 fps — the keyer receives nothing. With the UltraStudio connected, press Set up output device (one time)."}
    _record_device(r.home)
    state = r.engine.state()
    assert "noDevice" not in _ids(state)
    assert state["device"] == {"name": "UltraStudio HD Mini", "set": True}


def test_device_inactive_after_grace_is_w11(rig):
    r = rig(output_active=False)
    _record_device(r.home)
    r.run(lambda: r.engine.ensure_started(25, "external"))
    props = json.loads((r.tree / DECKLINK_PROPS).read_text())
    assert props["keyer"] == 1 and props["mode_id"] == 1215313201
    r.engine._liveness()
    assert r.engine.state()["state"] == "ready"
    assert not any(request[0] == "GetOutputStatus" for request in r.ws.requests)
    r.clock.now += 5
    r.engine._liveness()
    assert r.engine.state()["state"] == "ready"
    r.engine._liveness()
    state = r.engine.state()
    assert state["state"] == "blocked" and state["reason"] == "deviceInactive"
    w11 = next(w for w in state["warnings"] if w["id"] == "deviceInactive")
    assert w11["text"] == (
        "Alpha Keynote cannot open the UltraStudio. If ProPresenter is running, remove its SDI screen in Screen Configuration "
        "or quit ProPresenter; otherwise check the Thunderbolt cable and Desktop Video. Then press Release output and Take output again."
    )
    assert ("GetOutputStatus", {"outputName": "decklink_output"}) in r.ws.requests


def test_w11_raised_mid_show_and_cleared_on_recovery(rig):
    r = rig(output_active=True)
    _record_device(r.home)
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.clock.now += 5
    r.engine._liveness()
    assert r.engine.state()["state"] == "ready"
    r.ws.output_active = False
    r.engine._liveness()
    assert r.engine.state()["state"] == "ready"
    r.ws.output_active = True
    r.engine._liveness()
    r.ws.output_active = False
    r.engine._liveness()
    assert r.engine.state()["state"] == "ready", "a single false read after a true one must not flap"
    r.engine._liveness()
    state = r.engine.state()
    assert state["reason"] == "deviceInactive" and "deviceInactive" in _ids(state)
    r.ws.output_active = True
    r.engine._liveness()
    state = r.engine.state()
    assert state["state"] == "ready" and "deviceInactive" not in _ids(state)
    output_status = [request for request in r.ws.requests if request[0] == "GetOutputStatus"]
    assert output_status and all(request[1] == {"outputName": "decklink_output"} for request in output_status)
    assert {request[0] for request in r.ws.requests} == {"GetVersion", "GetOutputStatus"}


def test_w11_websocket_errors_are_unknown_reads(rig, monkeypatch):
    r = rig(output_active=False)
    _record_device(r.home)
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.clock.now += 5
    r.engine._liveness()
    real = managed_obs.ObsWebsocket

    class Broken:
        def __init__(self, *args, **kwargs): pass
        def __enter__(self): raise managed_obs.ObsWebsocketError("connection refused")
        def __exit__(self, *args): return None

    monkeypatch.setattr(managed_obs, "ObsWebsocket", Broken)
    for _ in range(2):
        r.engine._liveness()
    assert r.engine.state()["state"] == "ready"
    monkeypatch.setattr(managed_obs, "ObsWebsocket", real)
    r.engine._liveness()
    assert r.engine.state()["reason"] == "deviceInactive"


def test_w11_missing_output_counts_as_inactive(rig):
    r = rig(output_active=None)
    _record_device(r.home)
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.clock.now += 5
    r.engine._liveness()
    r.engine._liveness()
    assert r.engine.state()["reason"] == "deviceInactive"


def test_device_active_stays_ready(rig):
    r = rig(output_active=True)
    _record_device(r.home)
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.clock.now += 5
    r.engine._liveness()
    assert r.engine.state()["state"] == "ready"


def test_stale_decklink_file_is_removed_when_the_rate_has_no_mode(rig):
    r = rig()
    _record_device(r.home)
    r.run(lambda: r.engine.ensure_started(25, "external"))
    assert (r.tree / DECKLINK_PROPS).exists()
    r.run(lambda: r.engine.restart(30, "external"))
    assert not (r.tree / DECKLINK_PROPS).exists()


def test_no_output_status_request_without_a_device(rig):
    r = rig(output_active=False)
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.clock.now += 5
    r.engine._liveness()
    assert r.engine.state()["state"] == "ready"
    assert all(request[0] == "GetVersion" for request in r.ws.requests)


def test_setup_device_flow(rig):
    r = rig()
    state = r.run(lambda: r.engine.setup_device_begin(25))
    launch = r.launcher.launches[0]
    assert launch["hidden"] is False and "--minimize-to-tray" not in launch["args"]
    assert state["state"] == "blocked" and state["reason"] == "deviceSetup" and state["setup"] == 25
    assert not (r.tree / DECKLINK_PROPS).exists()
    (r.tree / DECKLINK_PROPS).parent.mkdir(parents=True, exist_ok=True)
    (r.tree / DECKLINK_PROPS).write_text(json.dumps({
        "device_hash": "hash-ultrastudio", "device_name": "UltraStudio HD Mini", "mode_id": 1215313201,
        "mode_name": "1080p25", "keyer": 1, "auto_start": True, "pixel_format": 1111970369}))
    state = r.run(r.engine.setup_device_done)
    assert r.launcher.terminated == [4242]
    assert state["state"] == "stopped" and state["setup"] is None
    assert r.engine.device() == DEVICE
    assert r.record()["cleanExit"] is True
    state = r.run(lambda: r.engine.ensure_started(25, "off"))
    assert r.launcher.launches[-1]["hidden"] is True
    assert json.loads((r.tree / DECKLINK_PROPS).read_text())["keyer"] == 0
    assert "obsUncleanExit" not in _ids(state)


def test_setup_adds_a_rate_to_the_same_device(rig):
    r = rig()
    _record_device(r.home)
    r.run(lambda: r.engine.setup_device_begin(30))
    assert not (r.tree / DECKLINK_PROPS).exists()
    (r.tree / DECKLINK_PROPS).parent.mkdir(parents=True, exist_ok=True)
    (r.tree / DECKLINK_PROPS).write_text(json.dumps({"device_hash": "hash-ultrastudio", "device_name": "UltraStudio HD Mini", "mode_id": 1215313200, "pixel_format": 1111970369}))
    r.run(r.engine.setup_device_done)
    assert r.engine.device()["modeIds"] == {"25": 1215313201, "30": 1215313200}


def test_operator_closing_obs_during_setup_is_not_w5(rig):
    r = rig()
    r.run(lambda: r.engine.setup_device_begin(25))
    r.launcher.alive_pids.clear()
    r.engine._liveness()
    state = r.engine.state()
    assert "obsExited" not in _ids(state) and state["reason"] == "deviceSetup"
    assert r.record()["cleanExit"] is False
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert "obsUncleanExit" in _ids(state)


# --- quit / stuck / show ------------------------------------------------------


def test_quit_is_clean(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    state = r.run(r.engine.quit)
    assert state["state"] == "stopped"
    assert r.launcher.terminated == [4242]
    assert r.engine.cdp_endpoint is None and r.engine.target_id is None


def test_quit_timeout_is_stuck_and_never_kills(rig, monkeypatch):
    signals: list[tuple[int, int]] = []
    monkeypatch.setattr(managed_obs.os, "kill", lambda pid, sig: signals.append((pid, sig)))
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.launcher.quits = False
    state = r.run(r.engine.quit)
    assert state["state"] == "stuck"
    w12 = next(w for w in state["warnings"] if w["id"] == "stuck")
    assert w12["text"] == "OBS is not responding to Quit. Press Show OBS and quit it from the OBS menu, then press Check again."
    assert r.launcher.terminated == [4242]
    assert 4242 in r.launcher.alive_pids
    assert signals == []
    assert not hasattr(r.launcher, "kill")
    assert r.run(r.engine.check)["state"] == "stuck"
    r.run(r.engine.show)
    assert r.launcher.shown == [4242]
    r.launcher.alive_pids.clear()
    state = r.run(r.engine.check)
    assert state["state"] == "stopped" and "stuck" not in _ids(state)
    assert r.record()["cleanExit"] is False, "only AK's own confirmed quit is clean"


def test_stuck_restart_does_not_relaunch_or_reseed(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    config = (r.tree / "plugin_config/obs-websocket/config.json").read_bytes()
    r.launcher.quits = False
    state = r.run(lambda: r.engine.restart(25, "external"))
    assert state["state"] == "stuck"
    assert len(r.launcher.launches) == 1
    assert (r.tree / "plugin_config/obs-websocket/config.json").read_bytes() == config


def test_seeding_refused_while_our_obs_is_alive(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    before = {path: path.read_bytes() for path in r.tree.rglob("*") if path.is_file()}
    with pytest.raises(ManagedObsError):
        r.engine._seed(_cfg())
    assert {path: path.read_bytes() for path in r.tree.rglob("*") if path.is_file()} == before


def test_show_activates_our_pid_only(rig):
    r = rig()
    r.run(r.engine.show)
    assert r.launcher.shown == []
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.run(r.engine.show)
    assert r.launcher.shown == [4242]


def test_restart_quits_then_launches(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    state = r.run(lambda: r.engine.restart(25, "external"))
    assert state["state"] == "ready"
    assert r.launcher.terminated == [4242]
    assert [launch["pid"] for launch in r.launcher.launches] == [4242, 4243]
    assert "obsUncleanExit" not in _ids(state)


def test_reset_page_navigates_the_target_back_to_blank(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.cdp.targets = [r.cdp.page("T1", "http://127.0.0.1:9/program.html")]
    r.run(lambda: r.engine.check(reset_page=True))
    assert r.cdp.navigations == [("T1", PAGE_URL)]
    assert r.engine.state()["state"] == "ready"


# --- orphans, unclean exits, lock -------------------------------------------


def test_orphan_is_always_quit_then_relaunched(rig):
    r = rig()
    r.home.mkdir(parents=True)
    (r.home / "ak-engine.json").write_text(json.dumps({"pid": 999, "launchDate": 1.0, "cdpPort": 1, "wsPort": 2, "cleanExit": False}))
    r.launcher.add(999, 1.0, r.home)
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert r.launcher.terminated == [999]
    assert [launch["pid"] for launch in r.launcher.launches] == [4242]
    assert state["state"] == "ready"
    assert "obsUncleanExit" in _ids(state), "W3 is snapshotted before orphan cleanup"
    assert r.record()["pid"] == 4242


def test_orphan_is_quit_on_first_check(rig):
    r = rig()
    r.home.mkdir(parents=True)
    (r.home / "ak-engine.json").write_text(json.dumps({"pid": 999, "launchDate": 1.0, "cdpPort": 1, "wsPort": 2, "cleanExit": False}))
    r.launcher.add(999, 1.0, r.home)
    state = r.run(r.engine.check)
    assert r.launcher.terminated == [999] and r.launcher.launches == []
    assert state["state"] == "stopped"


def test_previous_unclean_exit_is_w3(rig):
    r = rig()
    r.home.mkdir(parents=True)
    (r.home / "ak-engine.json").write_text(json.dumps({"pid": 999, "launchDate": 1.0, "cdpPort": 1, "wsPort": 2, "cleanExit": False}))
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["state"] == "ready"
    w3 = next(w for w in state["warnings"] if w["id"] == "obsUncleanExit")
    assert w3 == {"id": "obsUncleanExit", "severity": "warn",
                  "text": "OBS closed unexpectedly last time. It has been restarted; check the output before going live."}
    assert r.launcher.terminated == []


def test_restart_after_w5_shows_w3(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.launcher.alive_pids.clear()
    r.engine._liveness()
    state = r.run(lambda: r.engine.restart(25, "external"))
    assert state["state"] == "ready"
    assert _ids(state) == ["obsUncleanExit", "noDevice"]


def test_second_lock_holder_is_w13(rig):
    r = rig()
    r.run(r.engine.check)
    other = r.make()
    state = r.run(lambda: other.ensure_started(25, "external"), engine=other)
    assert state["state"] == "blocked" and state["reason"] == "ownedElsewhere"
    w13 = next(w for w in state["warnings"] if w["id"] == "ownedElsewhere")
    assert w13["text"] == f"The output engine is being used by another dashboard window (pid {os.getpid()}). Close that dashboard first."
    assert r.launcher.launches == []
    r.engine.close()
    state = r.run(other.check, engine=other)
    assert state["state"] == "stopped" and "ownedElsewhere" not in _ids(state)


def test_lock_is_held_after_quit(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.run(r.engine.quit)
    other = r.make()
    assert r.run(other.check, engine=other)["reason"] == "ownedElsewhere"


# --- invariants -------------------------------------------------------------


def test_sentinel_is_byte_identical_across_every_flow(rig):
    r = rig()
    sentinel = r.tree / ".sentinel"
    sentinel.mkdir(parents=True)
    (sentinel / "run_0123456789abcdef").write_bytes(b"\x00crash-marker\xff")
    before = {path.name: path.read_bytes() for path in sentinel.iterdir()}
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.run(lambda: r.engine.restart(30, "off"))
    r.launcher.alive_pids.clear()
    r.engine._liveness()
    r.run(lambda: r.engine.restart(25, "external"))
    r.run(lambda: r.engine.setup_device_begin(25))
    r.run(r.engine.setup_device_done)
    r.run(r.engine.check)
    r.run(r.engine.quit)
    assert {path.name: path.read_bytes() for path in sentinel.iterdir()} == before


def test_password_is_fresh_and_never_in_state_logs_record_or_args(rig, caplog):
    caplog.set_level(logging.DEBUG, logger="obed_edom.managed_obs")
    r = rig()
    passwords = []
    for action in (lambda: r.engine.ensure_started(25, "external"), lambda: r.engine.restart(25, "external")):
        state = r.run(action)
        assert state["state"] == "ready"
        passwords.append(r._tree_password())
    assert passwords[0] != passwords[1]
    assert all(len(password) >= 43 for password in passwords)
    exposed = [json.dumps(r.engine.state()), caplog.text, (r.home / "ak-engine.json").read_text(),
               json.dumps([launch["args"] + list(launch["env"].values()) for launch in r.launcher.launches], default=str),
               str(r.engine.cdp_endpoint)]
    for password in passwords:
        assert all(password not in text for text in exposed)
    assert "launched managed OBS" in caplog.text


# --- configure / has_orphan -------------------------------------------------


def test_configure_sets_preferred_rate_without_starting_or_locking(rig):
    r = rig()
    _record_device(r.home)
    assert "noDevice" not in _ids(r.engine.state())
    r.engine.configure(30, "off")
    state = r.engine.state()
    assert state["rate"] == {"output": 30, "canvas": "30", "source": 60}
    assert state["keyer"] == "off"
    assert state["state"] == "stopped"
    assert "No output device set for 30 fps" in next(w["text"] for w in state["warnings"] if w["id"] == "noDevice")
    assert r.engine._thread is None and r.engine._lock_file is None
    assert not (r.home / "ak-engine.lock").exists()
    assert r.launcher.launches == []
    other = r.make()
    assert r.run(other.check, engine=other)["state"] == "stopped"


@pytest.mark.parametrize("rate, keyer", [(50, "external"), (25, "internal")])
def test_configure_rejects_bad_input(rig, rate, keyer):
    r = rig()
    with pytest.raises(ValueError):
        r.engine.configure(rate, keyer)
    assert r.engine.state()["rate"]["output"] == 25


def test_configure_does_not_mask_a_needed_restart(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.engine.configure(30, "external")
    state = r.run(lambda: r.engine.ensure_started(30, "external"))
    assert len(r.launcher.launches) == 2 and r.launcher.terminated == [4242]
    assert state["rate"]["output"] == 30
    r.run(lambda: r.engine.ensure_started(30, "external"))
    assert len(r.launcher.launches) == 2


def test_has_orphan(rig):
    r = rig()
    assert r.engine.has_orphan() is False
    r.home.mkdir(parents=True)
    (r.home / "ak-engine.json").write_text(json.dumps({"pid": 999, "launchDate": 1.0, "cdpPort": 1, "wsPort": 2, "cleanExit": False}))
    assert r.engine.has_orphan() is False
    r.launcher.add(999, 1.0, r.home)
    assert r.engine.has_orphan() is True
    assert r.engine._thread is None and r.engine._lock_file is None
    assert not (r.home / "ak-engine.lock").exists()
    assert r.launcher.terminated == []
    r.run(r.engine.check)
    assert r.launcher.terminated == [999]
    assert r.engine.has_orphan() is False


def test_pid_reuse_by_a_non_ak_obs_is_untouched(rig):
    r = rig()
    r.home.mkdir(parents=True)
    (r.home / "ak-engine.json").write_text(json.dumps({"pid": 999, "launchDate": 1.0, "cdpPort": 1, "wsPort": 2, "cleanExit": True}))
    r.launcher.add(999, 1.0, None)
    r.launcher.add(998, 5.0, "/Users/someone")
    assert r.engine.has_orphan() is False
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["state"] == "ready"
    assert r.launcher.terminated == []
    r.run(r.engine.quit)
    r.run(r.engine.show)
    assert r.launcher.terminated == [4242] and r.launcher.shown == []
    assert {998, 999} <= r.launcher.alive_pids


def test_orphan_without_any_launch_date_is_found_by_marker(rig):
    r = rig()
    r.home.mkdir(parents=True)
    (r.home / "ak-engine.json").write_text(json.dumps({"pid": 999, "cdpPort": 1, "wsPort": 2, "cleanExit": False}))
    r.launcher.add(999, None, r.home)
    assert r.engine.has_orphan() is True
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert r.launcher.terminated == [999] and state["state"] == "ready"


def test_crash_after_launch_before_record_is_quit_before_seeding(rig):
    r = rig()
    r.home.mkdir(parents=True)
    (r.home / "ak-engine.json").write_text(json.dumps({"pid": 555, "launchDate": 1.0, "cdpPort": 1, "wsPort": 2, "cleanExit": True}))
    r.launcher.add(777, 50.0, r.home)
    config = r.tree / "plugin_config/obs-websocket/config.json"
    seeded_at_terminate: list[bool] = []
    r.launcher.on_terminate = lambda pid: seeded_at_terminate.append(config.exists())
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert r.launcher.terminated == [777]
    assert seeded_at_terminate == [False]
    assert state["state"] == "ready" and 777 not in r.launcher.alive_pids


def test_stuck_orphan_blocks_seeding(rig):
    r = rig()
    r.launcher.add(777, 50.0, r.home)
    r.launcher.quits = False
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["state"] == "stuck"
    assert r.launcher.launches == [] and not r.tree.exists()
    r.run(r.engine.show)
    assert r.launcher.shown == [777]


def test_current_engine_with_incomplete_identity_is_never_acted_on(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.launcher.dates[4242] = None
    state = r.run(r.engine.quit)
    assert r.launcher.terminated == []
    assert state["state"] == "blocked" and state["reason"] == "identityUnknown"
    r.run(r.engine.show)
    assert r.launcher.shown == []


def _tree_bytes(tree: Path) -> dict[str, bytes]:
    return {str(path.relative_to(tree)): path.read_bytes() for path in tree.rglob("*") if path.is_file()}


IDENTITY_UNKNOWN_TEXT = ("Alpha Keynote cannot confirm which OBS is its own, so it will not start or stop OBS. "
                         "Quit any OBS you opened yourself, then press Check again.")


@pytest.mark.parametrize("failure", ["marker", "processes"])
def test_unknown_identity_launches_nothing_writes_nothing_terminates_nothing(rig, failure):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.run(r.engine.quit)
    before = _tree_bytes(r.tree)
    record = (r.home / "ak-engine.json").read_bytes()
    r.launcher.add(777, 50.0, r.home)
    if failure == "marker":
        r.launcher.marker_unknown.add(777)
    else:
        r.launcher.processes_fail = True
    assert r.engine.has_orphan() is True, "unknown must make S5 run check() so the warning shows"
    for action in (lambda: r.engine.ensure_started(25, "external"), lambda: r.engine.restart(30, "off"),
                   lambda: r.engine.setup_device_begin(25), r.engine.check, r.engine.quit):
        state = r.run(action)
        assert state["state"] == "blocked" and state["reason"] == "identityUnknown"
    warning = next(w for w in state["warnings"] if w["id"] == "obsIdentityUnknown")
    assert warning == {"id": "obsIdentityUnknown", "severity": "block", "action": "check", "text": IDENTITY_UNKNOWN_TEXT}
    assert len(r.launcher.launches) == 1 and r.launcher.terminated == [4242]
    assert _tree_bytes(r.tree) == before
    assert (r.home / "ak-engine.json").read_bytes() == record
    r.launcher.marker_unknown.clear()
    r.launcher.processes_fail = False
    r.launcher.homes[777] = "/Users/someone"
    state = r.run(r.engine.check)
    assert state["state"] == "stopped" and "obsIdentityUnknown" not in _ids(state)
    assert 777 not in r.launcher.terminated


def test_readiness_requires_verified_ownership(rig):
    r = rig()
    r.launcher.on_launch = lambda launcher, pid: launcher.marker_unknown.add(pid)
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["state"] == "blocked" and state["reason"] == "identityUnknown"
    assert r.engine.target_id is None
    r.launcher.marker_unknown.clear()
    assert r.run(r.engine.check)["state"] == "ready"


@pytest.mark.parametrize("failure", ["marker", "processes"])
def test_liveness_on_unknown_identity_has_a_bounded_grace(rig, failure):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    requests_before = len(r.ws.requests)
    if failure == "marker":
        r.launcher.marker_unknown.add(4242)
    else:
        r.launcher.processes_fail = True
    r.engine._liveness()
    r.engine._liveness()
    assert r.engine.state()["state"] == "ready"
    assert len(r.ws.requests) == requests_before + 2, "read-only probes keep running during the grace"
    r.engine._liveness()
    state = r.engine.state()
    assert state["reason"] == "identityUnknown" and "obsIdentityUnknown" in _ids(state)
    state = r.run(r.engine.quit)
    assert r.launcher.terminated == [] and state["reason"] == "identityUnknown"
    r.launcher.marker_unknown.clear()
    r.launcher.processes_fail = False
    r.engine._liveness()
    assert r.engine.state()["state"] == "ready"


def test_terminate_acts_only_on_the_verified_process_object(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    real = r.launcher.terminate

    def reuse_pid_then_terminate(process):
        r.launcher.dates[4242] = 9999.0
        r.launcher.homes[4242] = None
        return real(process)

    r.launcher.terminate = reuse_pid_then_terminate
    state = r.run(r.engine.quit)
    assert r.launcher.terminated == []
    assert 4242 in r.launcher.alive_pids
    assert state["state"] == "stopped"
    assert r.record()["cleanExit"] is False, "an exit AK did not cause is never clean"


class _FakeNSApp:
    def __init__(self, pid, bundle, date, terminated=False):
        self.pid, self.bundle, self.date, self.dead, self.terminate_calls = pid, bundle, date, terminated, 0

    def processIdentifier(self): return self.pid
    def bundleIdentifier(self): return self.bundle
    def isTerminated(self): return self.dead
    def launchDate(self): return None if self.date is None else type("D", (), {"timeIntervalSince1970": lambda _self: self.date})()
    def terminate(self):
        self.terminate_calls += 1
        return True


@pytest.mark.parametrize("app, recorded, acts", [
    (_FakeNSApp(5, "com.obsproject.obs-studio", 100.0), 100.0, True),
    (_FakeNSApp(5, "com.obsproject.obs-studio", 100.0, terminated=True), 100.0, False),
    (_FakeNSApp(6, "com.obsproject.obs-studio", 100.0), 100.0, False),
    (_FakeNSApp(5, "org.example.other", 100.0), 100.0, False),
    (_FakeNSApp(5, "com.obsproject.obs-studio", 200.0), 100.0, False),
    (_FakeNSApp(5, "com.obsproject.obs-studio", None), 100.0, False),
    (_FakeNSApp(5, "com.obsproject.obs-studio", None), None, True),
])
def test_appkit_launcher_rechecks_the_same_object_before_acting(app, recorded, acts):
    process = ObsProcess(5, recorded, app)
    assert managed_obs.AppKitLauncher().terminate(process) is acts
    assert app.terminate_calls == (1 if acts else 0)


def test_launch_without_a_date_is_still_ours_by_marker(rig):
    r = rig()
    r.launcher.launch_date = lambda: None
    assert r.run(lambda: r.engine.ensure_started(25, "external"))["state"] == "ready"
    assert r.record()["launchDate"] is None
    assert r.run(r.engine.quit)["state"] == "stopped"
    assert r.launcher.terminated == [4242]


def test_our_own_engine_is_not_an_orphan(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    assert r.record()["pid"] == 4242
    assert r.engine.has_orphan() is False


# --- synchronous pending state (B1) -----------------------------------------


def test_actions_publish_pending_state_before_the_engine_runs_them(rig):
    r = rig()
    assert r.engine.active is False
    r.launcher.block = threading.Event()
    r.engine.ensure_started(25, "external")
    assert r.engine.state()["state"] == "starting" and "reason" not in r.engine.state()
    assert r.engine.active is True
    assert r.launcher.entered.wait(5)
    r.engine.quit()
    assert r.engine.state()["state"] == "quitting"
    r.engine.restart(25, "external")
    assert r.engine.state()["state"] == "starting"
    r.engine.setup_device_begin(25)
    assert r.engine.state()["state"] == "starting"
    r.engine.setup_device_done()
    assert r.engine.state()["state"] == "quitting"
    assert r.engine.active is True
    r.launcher.block.set()
    assert r.engine.wait_idle(15)
    state = r.engine.state()
    assert state["state"] == "stopped" and state["setup"] is None
    assert r.engine.active is False


def test_quit_is_quitting_until_the_engine_confirms(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    hold = threading.Event()
    r.launcher.on_terminate = lambda pid: hold.wait(15)
    r.engine.quit()
    assert r.engine.state()["state"] == "quitting" and r.engine.active is True
    assert r.engine.cdp_endpoint is not None
    hold.set()
    assert r.engine.wait_idle(15)
    assert r.engine.state()["state"] == "stopped" and r.engine.active is False


def test_noop_ensure_started_does_not_flash_starting(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.launcher.block = threading.Event()
    r.engine.ensure_started(25, "external")
    assert r.engine.state()["state"] == "ready"
    r.launcher.block.set()
    assert r.engine.wait_idle(15)


def test_active_follows_the_running_pid(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    assert r.engine.active is True
    r.launcher.alive_pids.clear()
    r.engine._liveness()
    assert r.engine.active is False


# --- shutdown / close (B3) --------------------------------------------------


def test_shutdown_during_a_full_readiness_wait_quits_and_releases(rig):
    r = rig()
    r.cdp.targets = []
    engine = r.make(clock=time.monotonic, sleep=time.sleep, ready_timeout_s=20.0, poll_s=0.05)
    launched = threading.Event()
    r.launcher.on_launch = lambda launcher, pid: launched.set()
    r.engine.close()
    engine.ensure_started(25, "external")
    assert launched.wait(5)
    started = time.monotonic()
    assert engine.shutdown(10) is True
    assert time.monotonic() - started < 5
    assert r.launcher.terminated == [4242] and 4242 not in r.launcher.alive_pids
    assert engine._thread is None and engine._lock_file is None
    assert r.record()["cleanExit"] is True
    engine.ensure_started(25, "external")
    assert len(r.launcher.launches) == 1, "no action runs after shutdown"
    other = r.make()
    assert r.run(other.check, engine=other)["state"] == "stopped"


def test_shutdown_keeps_the_lock_when_the_worker_does_not_finish(rig):
    r = rig()
    r.run(r.engine.check)
    r.launcher.block = threading.Event()
    r.engine.ensure_started(25, "external")
    assert r.launcher.entered.wait(5)
    assert r.engine.shutdown(0.2) is False
    assert r.engine._lock_file is not None
    other = r.make()
    assert r.run(other.check, engine=other)["reason"] == "ownedElsewhere"
    r.launcher.block.set()
    r.engine._thread.join(15)
    assert r.launcher.terminated == [4242], "the queued clean quit still runs"


def test_close_never_releases_the_lock_while_the_worker_is_alive(rig):
    r = rig()
    r.run(r.engine.check)
    r.launcher.block = threading.Event()
    r.engine.ensure_started(25, "external")
    assert r.launcher.entered.wait(5)
    assert r.engine.close(timeout=0.2) is False
    assert r.engine._lock_file is not None
    r.launcher.block.set()
    assert r.engine.close(timeout=15) is True
    assert r.engine._lock_file is None


def test_shutdown_without_a_worker_releases_the_lock(rig):
    r = rig()
    assert r.engine.shutdown(1) is True
    assert r.launcher.terminated == []


# --- bounded fail-closed liveness (M3) --------------------------------------


def test_three_cdp_failures_are_page_lost_and_a_success_resets(rig, monkeypatch):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    real = managed_obs._cdp_targets

    def broken(port, timeout=1.0):
        raise OSError("connection refused")

    monkeypatch.setattr(managed_obs, "_cdp_targets", broken)
    r.engine._liveness()
    r.engine._liveness()
    monkeypatch.setattr(managed_obs, "_cdp_targets", real)
    r.engine._liveness()
    monkeypatch.setattr(managed_obs, "_cdp_targets", broken)
    r.engine._liveness()
    r.engine._liveness()
    assert r.engine.state()["state"] == "ready"
    r.engine._liveness()
    state = r.engine.state()
    assert state["reason"] == "pageLost" and "obsPageLost" in _ids(state)
    monkeypatch.setattr(managed_obs, "_cdp_targets", real)
    r.engine._liveness()
    assert r.engine.state()["state"] == "ready"


def test_three_websocket_failures_are_obs_unreachable(rig, monkeypatch):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    real = managed_obs.ObsWebsocket

    class Broken:
        def __init__(self, *args, **kwargs): pass
        def __enter__(self): raise ObsWebsocketTimeout("no answer")
        def __exit__(self, *args): return None

    monkeypatch.setattr(managed_obs, "ObsWebsocket", Broken)
    r.engine._liveness()
    r.engine._liveness()
    assert r.engine.state()["state"] == "ready"
    r.engine._liveness()
    state = r.engine.state()
    assert state["state"] == "blocked" and state["reason"] == "obsUnreachable"
    w = next(w for w in state["warnings"] if w["id"] == "obsUnreachable")
    assert w == {"id": "obsUnreachable", "severity": "block", "action": "restart",
                 "text": "Alpha Keynote cannot reach OBS. Press Restart output engine."}
    monkeypatch.setattr(managed_obs, "ObsWebsocket", real)
    r.engine._liveness()
    state = r.engine.state()
    assert state["state"] == "ready" and "obsUnreachable" not in _ids(state)


def test_readiness_needs_page_and_version_in_the_same_pass(rig, monkeypatch):
    r = rig()
    pages = iter(["T1"] + [None] * 100)
    versions = iter([None] + [PINNED_OBS] * 100)
    monkeypatch.setattr(ManagedObs, "_page_target", lambda self: next(pages))
    monkeypatch.setattr(ManagedObs, "_obs_version", lambda self: next(versions))
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["state"] == "blocked" and state["reason"] == "timeout"


def test_readiness_accepts_a_later_pass_with_both(rig, monkeypatch):
    r = rig()
    pages = iter(["T1", "T1"])
    versions = iter([None, PINNED_OBS])
    monkeypatch.setattr(ManagedObs, "_page_target", lambda self: next(pages))
    monkeypatch.setattr(ManagedObs, "_obs_version", lambda self: next(versions))
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["state"] == "ready" and r.engine.target_id == "T1"


# --- version fix then check (M5) --------------------------------------------


def test_version_mismatch_then_install_then_check_is_ready(rig):
    r = rig(version="32.3.0")
    state = r.run(lambda: r.engine.ensure_started(25, "external"))
    assert state["reason"] == "obsVersion"
    _fake_app(r.app.parent, version="32.3.0")
    state = r.run(r.engine.check)
    assert state["reason"] == "obsVersion" and r.launcher.terminated == []
    _fake_app(r.app.parent, version=PINNED_OBS)
    r.ws.version = PINNED_OBS
    state = r.run(r.engine.check)
    assert state["state"] == "ready" and "obsVersion" not in _ids(state)
    assert r.launcher.terminated == [4242] and len(r.launcher.launches) == 2


# --- check(reset_page) (R2-1) -----------------------------------------------


def _hold(engine: ManagedObs) -> threading.Event:
    release = threading.Event()
    engine._submit(lambda: release.wait(15))
    return release


def test_check_reset_page_publishes_starting_until_it_has_run(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.cdp.targets = [r.cdp.page("T1", "http://127.0.0.1:9/program.html")]
    release = _hold(r.engine)
    r.engine.check(reset_page=True)
    assert r.engine.state()["state"] == "starting" and r.engine.active is True
    assert r.cdp.navigations == []
    release.set()
    assert r.engine.wait_idle(15)
    assert r.engine.state()["state"] == "ready"
    assert r.cdp.navigations == [("T1", PAGE_URL)]


def test_check_without_reset_publishes_nothing(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    release = _hold(r.engine)
    r.engine.check()
    assert r.engine.state()["state"] == "ready"
    release.set()
    assert r.engine.wait_idle(15)
    assert r.cdp.navigations == []


def test_check_reset_page_skips_an_engine_that_is_not_ready(rig):
    r = rig()
    r.cdp.targets = []
    r.run(lambda: r.engine.ensure_started(25, "external"))
    state = r.run(lambda: r.engine.check(reset_page=True))
    assert state["reason"] == "timeout" and r.cdp.navigations == []


# --- apply_settings (R2-2) --------------------------------------------------


def test_apply_settings_validates(rig):
    r = rig()
    for args in (("hdmi", 25, "external"), ("keyer", 50, "external"), ("screen", 25, "internal")):
        with pytest.raises(ValueError):
            r.engine.apply_settings(*args)
    assert r.engine._thread is None


@pytest.mark.parametrize("rate", [25, 30])
def test_apply_settings_keyer_never_launches(rig, rate):
    r = rig()
    release = _hold(r.engine)
    r.engine.apply_settings("screen", 25, "external")
    r.engine.apply_settings("keyer", rate, "external")
    assert r.engine.state()["state"] == "stopped"
    assert r.engine.state()["rate"]["output"] == rate
    release.set()
    assert r.engine.wait_idle(15)
    assert r.launcher.launches == [] and r.engine.state()["state"] == "stopped"
    assert r.engine._lock_file is None


def test_apply_settings_screen_then_keyer_same_rate_coalesces_to_no_change(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    release = _hold(r.engine)
    r.engine.apply_settings("screen", 25, "external")
    assert r.engine.state()["state"] == "quitting"
    r.engine.apply_settings("keyer", 25, "external")
    release.set()
    assert r.engine.wait_idle(15)
    assert r.engine.state()["state"] == "ready"
    assert r.launcher.terminated == [] and len(r.launcher.launches) == 1


def test_apply_settings_screen_then_keyer_new_rate_restarts_once(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    release = _hold(r.engine)
    r.engine.apply_settings("screen", 25, "external")
    r.engine.apply_settings("keyer", 30, "external")
    assert r.engine.state()["state"] in ("quitting", "starting")
    release.set()
    assert r.engine.wait_idle(15)
    state = r.engine.state()
    assert state["state"] == "ready" and state["rate"]["output"] == 30
    assert r.launcher.terminated == [4242] and len(r.launcher.launches) == 2


def test_apply_settings_keyer_rate_change_while_running_is_one_restart(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    release = _hold(r.engine)
    r.engine.apply_settings("keyer", 30, "external")
    assert r.engine.state()["state"] == "starting" and r.engine.active is True
    r.engine.apply_settings("keyer", 30, "off")
    release.set()
    assert r.engine.wait_idle(15)
    state = r.engine.state()
    assert state["state"] == "ready" and state["keyer"] == "off" and state["rate"]["output"] == 30
    assert r.launcher.terminated == [4242] and len(r.launcher.launches) == 2
    assert "FPSCommon=30\n" in (r.tree / "basic/profiles/AK/basic.ini").read_text()


def test_apply_settings_keyer_to_screen_quits(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    release = _hold(r.engine)
    r.engine.apply_settings("screen", 25, "external")
    assert r.engine.state()["state"] == "quitting"
    release.set()
    assert r.engine.wait_idle(15)
    state = r.engine.state()
    assert state["state"] == "stopped" and r.engine.active is False
    assert r.launcher.terminated == [4242] and r.record()["cleanExit"] is True


def test_apply_settings_keyer_same_settings_is_a_noop(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    r.engine.apply_settings("keyer", 25, "external")
    assert r.engine.state()["state"] == "ready"
    assert r.engine.wait_idle(15)
    assert r.launcher.terminated == [] and len(r.launcher.launches) == 1


# --- shutdown is terminal (R2-7) --------------------------------------------


def test_shutdown_then_close_keeps_the_clean_quit_before_releasing_the_lock(rig):
    r = rig()
    r.run(r.engine.check)
    r.launcher.block = threading.Event()
    lock_held_at_terminate: list[bool] = []
    r.launcher.on_terminate = lambda pid: lock_held_at_terminate.append(r.engine._lock_file is not None)
    r.engine.ensure_started(25, "external")
    assert r.launcher.entered.wait(5)
    assert r.engine.shutdown(0.1) is False
    assert r.engine.close(0.1) is False
    assert r.engine._lock_file is not None
    r.launcher.block.set()
    assert r.engine.close(15) is True
    assert r.launcher.terminated == [4242] and 4242 not in r.launcher.alive_pids
    assert lock_held_at_terminate == [True]
    assert r.engine._lock_file is None
    assert r.engine.shutdown(1) is True
    assert r.launcher.terminated == [4242]


def test_close_then_shutdown_still_quits(rig):
    r = rig()
    r.run(lambda: r.engine.ensure_started(25, "external"))
    assert r.engine.close(5) is True
    assert 4242 in r.launcher.alive_pids
    assert r.engine.shutdown(5) is True
    assert r.launcher.terminated == [4242] and 4242 not in r.launcher.alive_pids
